from pathlib import Path
from typing import Protocol, runtime_checkable
import pandas as pd

@runtime_checkable
class SourceAdapter(Protocol):
    name: str
    site_names: list[str]
    indoor_dash_is_dmy: bool
    aws_dash_is_dmy: bool
    def indoor_path(self, site: str) -> Path: ...
    def aws_path(self, site: str) -> Path: ...
    def housing_path(self, site: str) -> Path: ...
    def roof_map(self, site: str) -> dict: ...
    def floor_map(self, site: str) -> dict: ...
    def column_map(self, site: str) -> dict: ...
    def repair_rows(self, raw: pd.DataFrame, kind: str) -> pd.DataFrame: ...
